version: "3"
services:
  my-app:
    image: app-post-vue:0.0.2
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
